server:
  port: 8080

spring:
  application:
    name: cronaflow-scheduler

  # MongoDB Configuration
  mongodb:
    uri: mongodb://localhost:27017/cronaflow
    database: cronaflow

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: YOUR_EMAIL
    password: YOUR_APP_PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
